version: 0.2

phases:
  pre_build:
    commands:
      - npm test
  install:
    commands:
      - npm install
  build:
    commands:
      - npm run webpack
artifacts:
  files:
    - index.html
    - favicon.ico
    - resume.pdf
    - styles/main.css
    - images/*
    - dist/bundle.js
    - js/main.js
